### ISSUE TITLE
更新所有中文的標點符號

### ISSUE THREAD

**Issue by GodofMonkeys** [GodofMonkeys/Arma-III-Chinese-Localization-Enhanced#2]
現在中文增強包使用的標點符號都是英文的，需要全部更改為中文標點符號。

**Comment by GoldJohnKing** [comment]
个人不建议修改标点符号，因为根据目前的中文字体来看，中文标点会更贴近于它的后一个字，而非前一个字。

举例：“瞄准，发射”，如果使用英文逗号加空格，标点符号的位置会更贴近于”准“，这样符合正常的标点书写习惯和审美习惯，而使用中文逗号时，标点的位置更接近于”发“，而且距离”准“的距离相当大，这很明显是不符合正常书写和审美习惯的。

个人建议，在目前模组所采用的中文字库及字体没有解决标点符号的贴近问题之前，不要将全部英文标点置换为英文标点，以保证美观。

**Comment by GodofMonkeys** [comment]
@GoldJohnKing 感謝建議，目前團隊是先完成了所有標點符號的轉換。
再開始著手尋找新的替代字體，你的建議我到沒想到過，會在選擇字體時一併納入。

如有更多的建議與bug歡迎回復。
